version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: seubanco
      POSTGRES_USER: seuusuario
      POSTGRES_PASSWORD: suasenha
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ../backend/app-java
    container_name: springboot-app
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/seubanco
      SPRING_DATASOURCE_USERNAME: seuusuario
      SPRING_DATASOURCE_PASSWORD: suasenha
    networks:
      - app-network

  frontend:
    build:
      context: ../frontend/web-angular
    container_name: angular-app
    depends_on:
      - backend
    ports:
      - "4200:80"
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
